/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package aplicacioncomponentes;

import static aplicacioncomponentes.VentanaPrincipal.con;
import comp4.EvtElementoSeleccionadoJList;
import comp4.InElementoSelccionadoListener;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author samuel
 */

public class PanelBuscarProducto extends javax.swing.JPanel {
    private VentanaPrincipal principal;
    private int codigoPais = -1;
    private int codigoCategoria = -1;
    private int codigoProveedor = -1;
    private JTable tabla;
   
    public PanelBuscarProducto(VentanaPrincipal principal, JTable tabla) {
        initComponents();
        this.principal = principal;
        this.tabla = tabla;
        Connection con = null;
        buttonGenerarInforme.setEnabled(false);
        buttonInformeGrafico.setEnabled(false);
        buttonAgrupacion.setEnabled(false);
        
        
            try {
                String bbdd = "jdbc:hsqldb:hsql://localhost/";
                String usuario = "SA";
                String passw = "SA";
                Class.forName("org.hsqldb.jdbc.JDBCDriver");
                con = DriverManager.getConnection(bbdd, usuario, passw);
                String queryListaPaises = "SELECT codigo, nombre FROM PAISES";
                Statement stmt1 = con.createStatement();

                ResultSet resultSet = stmt1.executeQuery(queryListaPaises); 
                compPais.cargarLista(resultSet, "codigo", "nombre");
                
                
                
                stmt1.close();
                String queryListaCategorias = "SELECT CODIGO, NOMBRE FROM CATEGORIAS";
                Statement stmt3 = con.createStatement();

                ResultSet resultSet3 = stmt3.executeQuery(queryListaCategorias); 
                compCategoria.cargarLista(resultSet3, "codigo", "nombre");
                System.out.println(compCategoria.codigoElementoSeleccionado());
                stmt3.close();
                
                
                
                String queryListaProveedores = "SELECT codigo, nombre FROM proveedores";

                Statement stmt2 = con.createStatement();

                ResultSet resultSet2 = stmt2.executeQuery(queryListaProveedores);
                compProveedor.cargarLista(resultSet2, "codigo", "nombre");
                System.out.println(compProveedor.textoElementoSeleccionado());
                stmt2.close();
                
                
             }  catch (ClassNotFoundException ex) {
                 ex.printStackTrace();
            } catch (SQLException ex) {
                  ex.printStackTrace();
            }
            
            
            
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelFormularioBusqueda = new javax.swing.JPanel();
        buttonGenerarInforme = new javax.swing.JButton();
        compPais = new comp3_.Comp3();
        compCategoria = new comp3_.Comp3();
        compProveedor = new comp3_.Comp3();
        buttonInformeGrafico = new javax.swing.JButton();
        buttonAgrupacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panelBotones = new javax.swing.JPanel();
        reiniciarBoton = new javax.swing.JButton();
        buttonBuscar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1080, 400));

        panelFormularioBusqueda.setPreferredSize(new java.awt.Dimension(1080, 220));

        buttonGenerarInforme.setText("Generar informe");
        buttonGenerarInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenerarInformeActionPerformed(evt);
            }
        });

        compPais.setEtiqueta("País: ");

        compCategoria.setEtiqueta("Categoría: ");

        compProveedor.setEtiqueta("Proveedor: ");

        buttonInformeGrafico.setText("Informe y gráfico");
        buttonInformeGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInformeGraficoActionPerformed(evt);
            }
        });

        buttonAgrupacion.setText("Agrupación de datos (categoria)");
        buttonAgrupacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgrupacionActionPerformed(evt);
            }
        });

        jLabel1.setText("Informes");

        javax.swing.GroupLayout panelFormularioBusquedaLayout = new javax.swing.GroupLayout(panelFormularioBusqueda);
        panelFormularioBusqueda.setLayout(panelFormularioBusquedaLayout);
        panelFormularioBusquedaLayout.setHorizontalGroup(
            panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioBusquedaLayout.createSequentialGroup()
                .addGroup(panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormularioBusquedaLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(compPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(compCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(compProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelFormularioBusquedaLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(panelFormularioBusquedaLayout.createSequentialGroup()
                                .addComponent(buttonGenerarInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonInformeGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonAgrupacion)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panelFormularioBusquedaLayout.setVerticalGroup(
            panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormularioBusquedaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(compPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(compProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelFormularioBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonGenerarInforme, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonInformeGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAgrupacion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        reiniciarBoton.setText("Reiniciar");
        reiniciarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarBotonActionPerformed(evt);
            }
        });

        buttonBuscar.setText("Buscar");
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap(390, Short.MAX_VALUE)
                .addComponent(buttonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(reiniciarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reiniciarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelFormularioBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelFormularioBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void reiniciarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarBotonActionPerformed
        reiniciar();
        
        
    }//GEN-LAST:event_reiniciarBotonActionPerformed

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        codigoPais = compPais.codigoElementoSeleccionado();
            codigoCategoria = compCategoria.codigoElementoSeleccionado();
            codigoProveedor = compProveedor.codigoElementoSeleccionado();
            boolean activarBotones = principal.buscarProducto(codigoPais, codigoCategoria, codigoProveedor);
            if(activarBotones){
                buttonGenerarInforme.setEnabled(true);
                buttonInformeGrafico.setEnabled(true);
                buttonAgrupacion.setEnabled(true);
            }else{
                buttonGenerarInforme.setEnabled(false);
                buttonInformeGrafico.setEnabled(false);
                buttonAgrupacion.setEnabled(false);
            }
    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void buttonGenerarInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerarInformeActionPerformed
            //PASO 2
        InputStream vinculoarchivo = null;
        vinculoarchivo = getClass().getResourceAsStream("/recursos/ReportsJasper/Informe.jrxml");

        //PASO 3
        JasperReport jr = null;
         try {
          Map<String, Object> miMapa = new HashMap<>();
          if( codigoProveedor != -1)
          {
          miMapa.put("codProv", Integer.valueOf(codigoProveedor));
          }
          if( codigoCategoria != -1){
          miMapa.put("codCategoria", Integer.valueOf(codigoCategoria));
          }
          if( codigoPais != -1){
          miMapa.put("codPais", Integer.valueOf(codigoPais));
          }

          miMapa.put("imagenf", "recursos/ReportsJasper/imagenes/logo.png");
          jr = JasperCompileManager.compileReport(vinculoarchivo);
          JasperPrint jasperPrint = JasperFillManager.fillReport(jr, miMapa, con);
          JasperViewer visor = new JasperViewer(jasperPrint,false) ;
          visor.setVisible(true);

         } catch (JRException ex) {
                ex.printStackTrace();
         }
         

    }//GEN-LAST:event_buttonGenerarInformeActionPerformed

    private void buttonInformeGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInformeGraficoActionPerformed
        InputStream vinculoarchivo = null;
        vinculoarchivo = getClass().getResourceAsStream("/recursos/ReportsJasper/Informe2.jrxml");

        //PASO 3
        JasperReport jr = null;
         try {
          Map<String, Object> miMapa = new HashMap<>();
          if( codigoProveedor != -1)
          {
          miMapa.put("codProv", Integer.valueOf(codigoProveedor));
          }
          if( codigoCategoria != -1){
          miMapa.put("codCategoria", Integer.valueOf(codigoCategoria));
          }
          if( codigoPais != -1){
          miMapa.put("codPais", Integer.valueOf(codigoPais));
          }
          
          miMapa.put("imagenf", "recursos/ReportsJasper/imagenes/logo.png");
          jr = JasperCompileManager.compileReport(vinculoarchivo);
          JasperPrint jasperPrint = JasperFillManager.fillReport(jr, miMapa, con);
          JasperViewer visor = new JasperViewer(jasperPrint,false) ;
          visor.setVisible(true);

         } catch (JRException ex) {
                ex.printStackTrace();
         }
    }//GEN-LAST:event_buttonInformeGraficoActionPerformed

    private void buttonAgrupacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgrupacionActionPerformed
        InputStream vinculoarchivo = null;
        vinculoarchivo = getClass().getResourceAsStream("/recursos/ReportsJasper/Informe3.jrxml");

        //PASO 3
        JasperReport jr = null;
         try {
          Map<String, Object> miMapa = new HashMap<>();
          if( codigoProveedor != -1)
          {
          miMapa.put("codProv", Integer.valueOf(codigoProveedor));
          }
          if( codigoCategoria != -1){
          miMapa.put("codCategoria", Integer.valueOf(codigoCategoria));
          }
          if( codigoPais != -1){
          miMapa.put("codPais", Integer.valueOf(codigoPais));
          }
          
          miMapa.put("imagenf", "recursos/ReportsJasper/imagenes/logo.png");
          jr = JasperCompileManager.compileReport(vinculoarchivo);
          JasperPrint jasperPrint = JasperFillManager.fillReport(jr, miMapa, con);
          JasperViewer visor = new JasperViewer(jasperPrint,false) ;
          visor.setVisible(true);

         } catch (JRException ex) {
                ex.printStackTrace();
         }
    }//GEN-LAST:event_buttonAgrupacionActionPerformed

    public void reiniciar(){
        codigoPais = -1;
        codigoCategoria = -1;
        codigoProveedor = -1;
        compCategoria.reiniciarSeleccionLista();
        compPais.reiniciarSeleccionLista();
        compProveedor.reiniciarSeleccionLista();
        principal.cargarTablaProductos();
        buttonGenerarInforme.setEnabled(false);
        buttonInformeGrafico.setEnabled(false);
        buttonAgrupacion.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgrupacion;
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonGenerarInforme;
    private javax.swing.JButton buttonInformeGrafico;
    private comp3_.Comp3 compCategoria;
    private comp3_.Comp3 compPais;
    private comp3_.Comp3 compProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelFormularioBusqueda;
    private javax.swing.JButton reiniciarBoton;
    // End of variables declaration//GEN-END:variables
}
